frames: []

epochs-autoenc: 30
epochs-all: 100
epochs-dec: 80
epochs-dist: 20

# generate previews every x epochs
prev-period: 1

tgt-update-period: 100
cp-period: 2

# optimizer
lr-dist: 0.01
lr-autoenc: 0.001
lr-assign: 0.001
decay : 0.00004
lr-power : 0.98
momentum: 0.9
gamma: 0.1
alpha: 1
lambda-: 1e-7
beta: 0.8

# batch
batch-size: 2
batch-norm: True

# dataloader
n-segments-test: 300
delta-segments-test: 0
n-segments-train: 700
delta-segments-train: 300
n-workers: 0
cuda: False
n-ims-test: 5

# network input size
in-shape: 600
n-frames-epoch: 100

# augmentation
aug-noise: 0.1
aug-blur: 1.
aug-gamma: 0.05
aug-flip-proba: 0.5
aug-some: 2
aug-scale: 0.3
aug-rotate: 5.
aug-shear: 12.5

# sampling
n-edges: 100

n-clusters: 15

roi-output-size: 1
roi-spatial-scale: 1.0

with-agglo: False
with-pck: False
with-flow: False

linkage: 'ward'
