frames: []

epochs-autoenc: 150
epochs-dec: 100
epochs-dist: 200

# generate previews every x epochs
prev-period: 5

tgt-update-period: 10
proba-update-period: 5
cp-period: 5

# optimizer
lr-dist: 1e-3
lr-autoenc: 1e-2
lr-assign: 1e-3
decay : 2e-4
lr-power : 0.9
momentum: 0.9
gamma: 0.1
lambda-: 1e-5
beta: 1
alpha: 1

# batch
batch-size: 2
batch-norm: True

# dataloader
n-segments-test: 300
delta-segments-test: 0
n-segments-train: 700
delta-segments-train: 300
n-workers: 0
cuda: False
n-ims-test: 5

# network input size
in-shape: 600
n-frames-epoch: 100

# augmentation
aug-noise: 0.08
aug-blur-color: 30
aug-blur-space: 50
aug-gamma-low: 0.5
aug-gamma-high: 2.0
aug-flip-proba: 0.5
aug-some: 2
aug-scale: 0.3
aug-rotate: 10.
aug-shear: 20.

# sampling
n-edges-ratio: 0.05
nn-radius: 0.1

n-clusters: 15
embedded-dims: 15

roi-output-size: 1
roi-spatial-scale: 1.0

with-agglo: False
with-pck: False
with-flow: False
reduc-method: 'lfda'
ml-up-thr: 0.7
ml-down-thr: 0.3
bag-t: 300
bag-n-feats : 0.1
bag-max-depth : 64

linkage: 'ward'

thr-assign: 0.001
