frames: []

epochs-autoenc: 80
epochs-dec: 100
epochs-dist: 100

# generate previews every x epochs
prev-period: 1

tgt-update-period: 800
proba-update-period: 10
cp-period: 5

# optimizer
lr-dist: 0.1
lr-autoenc: 0.01
lr-assign: 1e-4
decay : .01
lr-power : 0.97
momentum: 0.9
gamma: 2e2
lambda-: 1
alpha: 1
beta: 0.8

# batch
batch-size: 2
batch-norm: True

# dataloader
n-segments-test: 300
delta-segments-test: 0
n-segments-train: 700
delta-segments-train: 300
n-workers: 0
cuda: False
n-ims-test: 5

# network input size
in-shape: 600
n-frames-epoch: 100

# augmentation
aug-noise: 0.1
aug-blur: 1.
aug-gamma: 0.05
aug-flip-proba: 0.5
aug-some: 2
aug-scale: 0.3
aug-rotate: 5.
aug-shear: 12.5

# sampling
n-edges-ratio: 0.05
nn-radius: 0.1

n-clusters: 15
embedded-dims: 10

roi-output-size: 1
roi-spatial-scale: 1.0

with-agglo: False
with-pck: False
with-flow: False
reduc-method: 'lfda'
ml-up-thr: 0.5
ml-down-thr: 0.5
bag-t: 300

linkage: 'ward'

thr-assign: 0.001
