frames: []

epochs-autoenc: 80
epochs-dec: 150
epochs-dist: 50

# generate previews every x epochs
prev-period: 1

tgt-update-period: 300
cp-period: 5

# optimizer
lr-dist: 0.1
lr-autoenc: 0.1
lr-assign: 0.1
decay : 0.00004
lr-power : 0.98
momentum: 0.9
gamma: 0.1
alpha: 1
lambda-: 1e-7
beta: 0.8

# batch
batch-size: 2
batch-norm: True

# dataloader
n-segments-test: 300
delta-segments-test: 0
n-segments-train: 700
delta-segments-train: 300
n-workers: 0
cuda: False
n-ims-test: 5

# network input size
in-shape: 600
n-frames-epoch: 100

# augmentation
aug-noise: 0.1
aug-blur: 1.
aug-gamma: 0.05
aug-flip-proba: 0.5
aug-some: 2
aug-scale: 0.3
aug-rotate: 5.
aug-shear: 12.5

# sampling
n-edges: 200
nn-radius: 0.05

n-clusters: 30
embedded-dims: 30

roi-output-size: 1
roi-spatial-scale: 1.0

with-agglo: False
with-pck: False
with-flow: False

linkage: 'ward'

thr-assign: 0.05
